package com.smbshare

import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext

/**
 * SMB 配置文件生成器
 * 根据参数生成 Samba smb.conf
 */
class SmbConfigGenerator {

    /**
     * 生成 smb.conf 内容
     */
    fun generateContent(
        shareName: String = DEFAULT_SHARE_NAME,
        sharePath: String = DEFAULT_SHARE_PATH,
        workgroup: String = DEFAULT_WORKGROUP,
        protocolMin: String = DEFAULT_PROTOCOL_MIN,
        protocol: String = DEFAULT_PROTOCOL,
        netbiosDisabled: Boolean = true,
        guestAccess: Boolean = true,
        readOnly: Boolean = false,
        forceUser: String = "root",
        interfaces: String = "*"
    ): String {
        val sb = StringBuilder()
        sb.appendLine("# Generated by SMBShareStandalone")
        sb.appendLine("[global]")

        if (netbiosDisabled) {
            sb.appendLine("disable netbios = Yes")
        }
        sb.appendLine("enable core files = no")
        sb.appendLine("unix charset = UTF-8")
        sb.appendLine("server min protocol = $protocolMin")
        sb.appendLine("timestamp logs = no")
        sb.appendLine("log level = 0")
        sb.appendLine("protocol = $protocol")
        sb.appendLine("interfaces = $interfaces")
        sb.appendLine("workgroup = $workgroup")
        sb.appendLine("server string = $shareName")

        sb.appendLine("remote announce = 255.255.255.255")
        sb.appendLine("load printers = no")
        sb.appendLine("printcap name = /dev/null")
        sb.appendLine("disable spoolss = yes")
        sb.appendLine("deadtime = 60")
        sb.appendLine("delete readonly = yes")
        sb.appendLine("nt acl support = no")
        sb.appendLine("inherit permissions = yes")
        sb.appendLine("local master = no")
        sb.appendLine("unix extensions = yes")

        if (guestAccess) {
            sb.appendLine("security = user")
            sb.appendLine("guest account = nobody")
            sb.appendLine("map to guest = Bad User")
        }

        sb.appendLine("socket options = TCP_NODELAY IPTOS_LOWDELAY")
        sb.appendLine("read raw = yes")
        sb.appendLine("write raw = yes")
        sb.appendLine("max xmit = 131072")
        sb.appendLine()

        // Share definition
        sb.appendLine("[$shareName]")
        sb.appendLine("comment = Shared by SMBShareStandalone")
        if (readOnly) {
            sb.appendLine("read only = yes")
        } else {
            sb.appendLine("read only = no")
        }
        sb.appendLine("force user = $forceUser")
        sb.appendLine("path = $sharePath")
        sb.appendLine("map readonly = permissions")

        return sb.toString()
    }

    /**
     * 将配置文件写入指定路径 (需要 root 权限)
     */
    suspend fun writeConfigFile(
        configPath: String = DEFAULT_CONFIG_PATH,
        shareName: String = DEFAULT_SHARE_NAME,
        sharePath: String = DEFAULT_SHARE_PATH,
        workgroup: String = DEFAULT_WORKGROUP,
        shellExecutor: ShellExecutor = ShellExecutor()
    ): Boolean {
        return withContext(Dispatchers.IO) {
            val config = generateContent(
                shareName = shareName,
                sharePath = sharePath,
                workgroup = workgroup
            )

            // 创建目录
            val dirPath = configPath.substringBeforeLast("/")
            shellExecutor.execute("mkdir -p $dirPath", asRoot = true)

            // 写入配置文件
            // 通过 heredoc 方式写入，避免特殊字符问题
            val writeCmd = buildString {
                append("cat > $configPath << 'SMBEOF'\n")
                append(config)
                append("SMBEOF")
            }
            val result = shellExecutor.execute(writeCmd, asRoot = true)
            result.isSuccess
        }
    }

    companion object {
        const val DEFAULT_CONFIG_PATH = "/data/zb/samba/smb.conf"
        const val DEFAULT_SHARE_NAME = "rannki_smb"
        const val DEFAULT_SHARE_PATH = "/sdcard"
        const val DEFAULT_WORKGROUP = "WORKGROUP"
        const val DEFAULT_PROTOCOL_MIN = "SMB3_02"
        const val DEFAULT_PROTOCOL = "SMB3"

        const val SMB_INSTALL_DIR = "/data/zb"
        const val SMB_LIB_DIR = "/data/zb/lib"
        const val SMB_CONFIG_DIR = "/data/zb/samba"
        const val SMB_EXECUTABLE = "/data/zb/smbd0"
    }
}