package com.smbshare

import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext

/**
 * SMB 配置文件生成器
 * 根据参数生成 Samba smb.conf
 *
 * 路径与默认值的唯一事实源 (SSOT)。
 * 设计为 object: 所有方法无状态，不依赖任何实例字段，全局共享单一实例即可。
 */
object SmbConfigGenerator {

    const val DEFAULT_CONFIG_PATH = "/data/zb/samba/smb.conf"
    const val DEFAULT_SHARE_NAME = "android_smb"
    const val DEFAULT_SHARE_PATH = "/sdcard"
    const val DEFAULT_WORKGROUP = "WORKGROUP"
    const val DEFAULT_PROTOCOL_MIN = "SMB3_02"
    const val DEFAULT_PROTOCOL = "SMB3"

    const val SMB_INSTALL_DIR = "/data/zb"
    const val SMB_LIB_DIR = "/data/zb/lib"
    const val SMB_CONFIG_DIR = "/data/zb/samba"
    const val SMB_EXECUTABLE = "/data/zb/smbd0"

    /**
     * 生成 smb.conf 内容
     */
    fun generateContent(
        shareName: String = DEFAULT_SHARE_NAME,
        sharePath: String = DEFAULT_SHARE_PATH,
        workgroup: String = DEFAULT_WORKGROUP,
        protocolMin: String = DEFAULT_PROTOCOL_MIN,
        protocol: String = DEFAULT_PROTOCOL,
        netbiosDisabled: Boolean = true,
        guestAccess: Boolean = true,
        readOnly: Boolean = false,
        forceUser: String = "root",
        interfaces: String = "*",
        secureMode: Boolean = false,
        hostsAllow: String? = null
    ): String {
        // 净化用户输入, 防 smb.conf 注入
        val safeName = sanitizeShareName(shareName)
        val safePath = sanitizeSharePath(sharePath)
        val safeHostsAllow = hostsAllow?.let { sanitizeHostsAllow(it) }
        // 只读模式下以 nobody 访问文件系统, 减少 root 身份的暴露面
        val effectiveForceUser = if (readOnly && forceUser == "root") "nobody" else forceUser

        val sb = StringBuilder()
        sb.appendLine("# Generated by SMBShareStandalone")
        sb.appendLine("[global]")

        if (netbiosDisabled) {
            sb.appendLine("disable netbios = Yes")
            // remote announce 依赖 NetBIOS 广播；NetBIOS 已禁用时该项无效，不输出
        }
        sb.appendLine("enable core files = no")
        sb.appendLine("unix charset = UTF-8")
        sb.appendLine("server min protocol = $protocolMin")
        sb.appendLine("timestamp logs = no")
        sb.appendLine("log level = 0")
        sb.appendLine("protocol = $protocol")
        sb.appendLine("interfaces = $interfaces")
        sb.appendLine("workgroup = $workgroup")
        sb.appendLine("server string = $safeName")

        // 安全模式: 强制 SMB 加密传输 + 限定来源网段 (hosts allow)
        if (secureMode) {
            sb.appendLine("smb encrypt = required")
            if (!safeHostsAllow.isNullOrBlank()) {
                sb.appendLine("hosts allow = $safeHostsAllow")
            }
        }

        sb.appendLine("load printers = no")
        sb.appendLine("printcap name = /dev/null")
        sb.appendLine("disable spoolss = yes")
        sb.appendLine("deadtime = 60")
        sb.appendLine("delete readonly = yes")
        sb.appendLine("nt acl support = no")
        sb.appendLine("inherit permissions = yes")
        sb.appendLine("local master = no")
        sb.appendLine("unix extensions = yes")

        if (guestAccess) {
            sb.appendLine("security = user")
            sb.appendLine("guest account = nobody")
            sb.appendLine("map to guest = Bad User")
        }

        sb.appendLine("socket options = TCP_NODELAY IPTOS_LOWDELAY")
        sb.appendLine("read raw = yes")
        sb.appendLine("write raw = yes")
        sb.appendLine("max xmit = 131072")
        sb.appendLine()

        // Share definition
        sb.appendLine("[$safeName]")
        sb.appendLine("comment = Shared by SMBShareStandalone")
        sb.appendLine("read only = ${if (readOnly) "yes" else "no"}")
        sb.appendLine("force user = $effectiveForceUser")
        sb.appendLine("path = $safePath")
        sb.appendLine("map readonly = permissions")

        return sb.toString()
    }

    /**
     * 将配置文件写入指定路径 (需要 root 权限)
     */
    suspend fun writeConfigFile(
        configPath: String = DEFAULT_CONFIG_PATH,
        shareName: String = DEFAULT_SHARE_NAME,
        sharePath: String = DEFAULT_SHARE_PATH,
        workgroup: String = DEFAULT_WORKGROUP,
        readOnly: Boolean = false,
        secureMode: Boolean = false,
        hostsAllow: String? = null,
        shellExecutor: ShellExecutor
    ): Boolean {
        return withContext(Dispatchers.IO) {
            val config = generateContent(
                shareName = shareName,
                sharePath = sharePath,
                workgroup = workgroup,
                readOnly = readOnly,
                secureMode = secureMode,
                hostsAllow = hostsAllow
            )

            // 创建目录
            val dirPath = configPath.substringBeforeLast("/")
            shellExecutor.execute("mkdir -p \"$dirPath\"", asRoot = true)

            // 通过 heredoc 方式写入，避免特殊字符问题 (heredoc 引号 'SMBEOF' 关闭 shell 展开)
            val writeCmd = buildString {
                append("cat > \"$configPath\" << 'SMBEOF'\n")
                append(config)
                append("SMBEOF")
            }
            val result = shellExecutor.execute(writeCmd, asRoot = true)
            result.isSuccess
        }
    }

    /**
     * 由设备局域网 IPv4 (如 192.168.1.5) 推导 /24 网段前缀 (如 192.168.1.),
     * 供 smb.conf `hosts allow` 限定来源。家用局域网多为 /24，前缀形式被 Samba 直接接受。
     * 非法/非 IPv4 返回 null。
     */
    fun lanPrefixFromIp(ip: String): String? {
        val parts = ip.trim().split(".")
        if (parts.size != 4) return null
        if (parts.any { it.toIntOrNull() == null }) return null
        return "${parts[0]}.${parts[1]}.${parts[2]}."
    }

    /**
     * 净化共享名: 仅保留 [A-Za-z0-9_-]，截断到 32 字符。
     * 空或全部被滤掉则回退默认名，防止空串生成非法 [] 段头 / 换行注入新 share 段。
     */
    private fun sanitizeShareName(raw: String): String {
        val cleaned = raw.trim()
            .filter { it.isLetterOrDigit() || it == '_' || it == '-' }
            .take(32)
        return cleaned.ifBlank { DEFAULT_SHARE_NAME }
    }

    /**
     * 净化共享路径: 剔除换行/回车 (防 path 行换行后注入新 share 段)，要求绝对路径。
     * 非绝对路径回退默认，避免生成相对路径的非法 smb.conf。
     */
    private fun sanitizeSharePath(raw: String): String {
        val cleaned = raw.replace("\r", "").replace("\n", "").trim()
        return if (cleaned.startsWith("/")) cleaned else DEFAULT_SHARE_PATH
    }

    /**
     * 净化 hosts allow 值: 仅保留 ASCII IP/点/斜杠/逗号/空格，剔除换行防注入新段。
     * 使用明确 ASCII 范围 (而非 isLetterOrDigit())，避免放行 Unicode 字母 (如 α、中)。
     */
    private fun sanitizeHostsAllow(raw: String): String {
        return raw.replace("\r", "").replace("\n", "").trim()
            .filter { c ->
                c in '0'..'9' || c in 'a'..'z' || c in 'A'..'Z' ||
                c == '.' || c == '/' || c == ',' || c == ' '
            }
            .trim()
    }
}
