#!/system/bin/sh
#
# SMB 服务启动脚本
# 从 com.example.ourom libourom.so 逆向提取
# 基于 SambaDroid 框架
#

SMB_DIR="/data/zb"
SMB_CONFIG_DIR="$SMB_DIR/samba"
SMB_CONFIG="$SMB_CONFIG_DIR/smb.conf"
SMB_EXEC="$SMB_DIR/smbd0"
DBUS_EXEC="$SMB_DIR/dbus-daemon"
SHARE_NAME="rannki_smb"
SHARE_PATH="/sdcard"
WORKGROUP="WORKGROUP"

echo "========================================"
echo "  SMB Share Standalone — 启动脚本"
echo "========================================"
echo ""

# 检查 root
if [ "$(id -u)" -ne 0 ]; then
    echo "[ERROR] 需要 root 权限"
    exit 1
fi

# 查找 busybox
BUSYBOX=""
for B in /nitiFile/busybox /data/assetsFairu/busybox /system/xbin/busybox /system/bin/busybox; do
    if [ -f "$B" ]; then
        BUSYBOX="$B"
        break
    fi
done
if [ -z "$BUSYBOX" ]; then
    BUSYBOX="busybox"
fi

echo "[INFO] busybox: $BUSYBOX"

# 检查二进制文件
if [ ! -f "$SMB_EXEC" ]; then
    echo "[ERROR] smbd0 未找到: $SMB_EXEC"
    echo "[INFO] 请先解压 smb3.tgz 到 $SMB_DIR"
    exit 1
fi
if [ ! -f "$DBUS_EXEC" ]; then
    echo "[ERROR] dbus-daemon 未找到: $DBUS_EXEC"
    exit 1
fi

echo "[INFO] smbd0: OK"
echo "[INFO] dbus-daemon: OK"

# 停止已有实例
echo ""
echo "[STEP] 停止已有实例..."
$BUSYBOX killall -9 smbd0 2>/dev/null
$BUSYBOX killall -9 dbus-daemon 2>/dev/null
sleep 1

# 创建目录
echo "[STEP] 创建目录..."
mkdir -p "$SMB_DIR"
mkdir -p "$SMB_DIR/lib"
mkdir -p "$SMB_CONFIG_DIR"

# 生成 smb.conf
echo "[STEP] 生成 smb.conf..."
cat > "$SMB_CONFIG" << SMBCONFEOF
# Generated by SMBShareStandalone
[global]
disable netbios = Yes
enable core files = no
unix charset = UTF-8
server min protocol = SMB3_02
timestamp logs = no
log level = 0
protocol = SMB3
interfaces = *
workgroup = $WORKGROUP
server string = $SHARE_NAME
remote announce = 255.255.255.255
load printers = no
printcap name = /dev/null
disable spoolss = yes
deadtime = 60
delete readonly = yes
nt acl support = no
inherit permissions = yes
local master = no
unix extensions = yes
security = user
guest account = nobody
map to guest = Bad User
socket options = TCP_NODELAY IPTOS_LOWDELAY
read raw = yes
write raw = yes
max xmit = 131072

[$SHARE_NAME]
comment = Shared Data
read only = no
force user = root
path = $SHARE_PATH
map readonly = permissions
SMBCONFEOF

echo "[INFO] 配置文件: $SMB_CONFIG"

# 启动 dbus-daemon
# setsid 让 dbus 脱离当前会话, 脚本退出时不会被 SIGHUP 连带杀掉
echo "[STEP] 启动 dbus-daemon..."
setsid "$DBUS_EXEC" --system </dev/null >/dev/null 2>&1 &

# 等待 dbus 启动
sleep 1

# 启动 smbd0 (-D 自身 daemon 化)
echo "[STEP] 启动 smbd0..."
export TMPDIR="$SMB_DIR/lib"
"$SMB_EXEC" -D -s "$SMB_CONFIG" </dev/null >/dev/null 2>&1

sleep 2

# 验证
if $BUSYBOX pidof smbd0 > /dev/null 2>&1; then
    echo ""
    echo "========================================"
    echo "  SMB 服务已成功启动!"
    echo "========================================"
    echo ""
    echo "共享名: $SHARE_NAME"
    echo "共享路径: $SHARE_PATH"
    echo ""

    # 获取 IP
    IP=$(ip addr show wlan0 2>/dev/null | grep 'inet ' | awk '{print $2}' | cut -d'/' -f1)
    if [ -z "$IP" ]; then
        IP=$(ip addr show eth0 2>/dev/null | grep 'inet ' | awk '{print $2}' | cut -d'/' -f1)
    fi
    if [ -n "$IP" ]; then
        echo "访问地址: \\\\$IP\\$SHARE_NAME"
        echo "           smb://$IP/$SHARE_NAME"
    fi
else
    echo ""
    echo "[ERROR] SMB 服务启动失败"
    echo ""
    echo "诊断信息:"
    echo "---"
    ls -la "$SMB_EXEC"
    ls -la "$DBUS_EXEC"
    cat "$SMB_CONFIG"
    echo "---"
fi